version: "3"
services:
  db_one:
    image: mysql:5.7
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3400:3306"
    volumes:
      - db_data_one:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: db_password
      WORDPRESS_WPLANG: zh-CN
  wordpress_one:
    depends_on:
      - db_one
    # image: wordpress:latest
    image: wordpress:php7.4-apache
    ports:
      - "9000:80"
    restart: always
    volumes:
      - wordpress_data_one:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db_one:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: db_password
volumes:
  db_data_one:
  wordpress_data_one:
